function renderEvidence(items=[]){$('#evidenceItems').innerHTML=items.map(x=>`<div class="evidence-item" data-eid="${x.id}"><input class="ev-note" placeholder="Evidence note" value="${esc(x.note)}"><input class="ev-url" placeholder="URL/ref" value="${esc(x.url)}"><select class="ev-strength">${Array.from({length:10},(_,n)=>`<option value="${n+1}" ${x.strength===n+1?'selected':''}>Strength ${n+1}</option>`).join('')}</select><button class="btn btn-danger ev-remove" type="button">Remove</button></div>`).join('')}
$('#addEvidence').addEventListener('click',()=>{$('#evidenceItems').insertAdjacentHTML('beforeend',`<div class="evidence-item" data-eid="${uid()}"><input class="ev-note" placeholder="Evidence note"><input class="ev-url" placeholder="URL/ref"><select class="ev-strength">${Array.from({length:10},(_,n)=>`<option value="${n+1}">Strength ${n+1}</option>`).join('')}</select><button class="btn btn-danger ev-remove" type="button">Remove</button></div>`)});document.addEventListener('click',e=>{if(e.target.classList.contains('ev-remove'))e.target.closest('.evidence-item').remove()});
function formScores(){return{impact:+$('#impact').value,evidence:+$('#evidence').value,revenue:+$('#revenue').value,completion:+$('#completion').value,cost:+$('#cost').value,time:+$('#timeBurden').value,dependencies:+$('#dependencyBurden').value}}
function updateLiveScore(){const s=formScores(),p=(s.impact*s.evidence*s.revenue*s.completion)/(s.cost*s.time*s.dependencies);$('#liveScore').textContent='Priority '+p.toFixed(2)}
[['impact','impactOut'],['evidence','evidenceOut'],['revenue','revenueOut'],['completion','completionOut'],['cost','costOut'],['timeBurden','timeOut'],['dependencyBurden','depOut']].forEach(([a,b])=>$('#'+a).addEventListener('input',()=>{$('#'+b).value=$('#'+a).value;updateLiveScore()}));
$('#ideaForm').addEventListener('submit',async e=>{e.preventDefault();const id=$('#ideaId').value,existing=id?vault.ideas.find(i=>i.id===id):null,next=$('#ideaState').value;const check=canTransition(existing||{state:'CANDIDATE',id:''},next);if(!check.ok)return toast(check.msg,true);if(next==='MERGED'&&!$('#relatedIds').value.trim()&&!$('#parentId').value.trim())if(!confirm('MERGED is stronger when the destination/related branch is recorded. Save anyway?'))return;const evidenceItems=$$('.evidence-item').map(el=>({id:el.dataset.eid||uid(),note:el.querySelector('.ev-note').value,url:el.querySelector('.ev-url').value,strength:+el.querySelector('.ev-strength').value}));const obj=normalizeIdea({id:existing?.id,title:$('#ideaTitle').value,thesis:$('#ideaThesis').value,description:$('#ideaDescription').value,state:next,expectedValue:$('#expectedValue').value,origin:$('#origin').value,sourceRef:$('#sourceRef').value,tags:$('#tags').value,parentId:$('#parentId').value,relatedIds:$('#relatedIds').value,dependencies:$('#dependencies').value,blockers:$('#blockers').value,nextAction:$('#nextAction').value,reactivateOn:$('#reactivateOn').value,reactivationTrigger:$('#reactivationTrigger').value,stopReason:$('#stopReason').value,ownerNotes:$('#ownerNotes').value,scores:formScores(),evidenceItems,transcript:{raw:$('#rawTranscript').value,canonicalEntity:$('#canonicalEntity').value,confidence:+$('#entityConfidence').value,verified:$('#entityVerified').checked},monetizedAmount:$('#monetizedAmount').value,receiptNote:$('#receiptNote').value,createdAt:existing?.createdAt||now()});if(obj.transcript.raw&&obj.transcript.canonicalEntity&&!obj.transcript.verified)toast('Entity stored as UNVERIFIED; canonical history will not be overwritten.');if(existing){const idx=vault.ideas.findIndex(i=>i.id===id);vault.ideas[idx]=obj}else vault.ideas.push(obj);$('#ideaModal').classList.add('hidden');await saveVault({type:existing?'IDEA_UPDATED':'IDEA_CAPTURED',message:`${obj.title} → ${obj.state}`});toast(existing?'Asset updated.':'Idea captured and preserved.')});
function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;document.body.appendChild(a);a.click();URL.revokeObjectURL(a.href);a.remove()}
async function encryptedBackup(){const meta=await idbGet(META_STORE,'crypto'),rec=await idbGet(VAULT_STORE,'encrypted');return{format:'amplification-governor-encrypted-backup',version:1,exportedAt:now(),crypto:meta,vault:rec}}
$('#downloadEncrypted').addEventListener('click',async()=>{download(`amplification-governor-encrypted-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(await encryptedBackup(),null,2));await saveVault({type:'BACKUP_EXPORTED',message:'Encrypted vault backup downloaded.'});toast('Encrypted backup downloaded.')});
$('#restoreEncrypted').addEventListener('click',()=>$('#restoreFile').click());$('#restoreFile').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{const b=JSON.parse(await f.text());if(b.format!=='amplification-governor-encrypted-backup'||!b.crypto?.salt||!b.vault?.ciphertext)throw new Error('Not a valid encrypted Governor backup.');if(!confirm('Restore this encrypted backup? It will replace the current local vault on this device.'))return;await idbSet(META_STORE,'crypto',b.crypto);await idbSet(VAULT_STORE,'encrypted',b.vault);toast('Backup restored. Locking now; unlock with the backup passphrase.');setTimeout(lockApp,900)}catch(err){toast(err.message,true)}finally{e.target.value=''}});
function exportPlain(){return{format:'amplification-governor-plain-export',version:1,exportedAt:now(),vault}}
