import{createInitialState,appendExperience,runNREM,runREM,verifyCandidate,commitVerifiedTransition,verifyChronosChain,compressionRatio,serializeState,importState}from'./engine.mjs';
const STORAGE='victor-rem-lab-v1';let state=load();const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function load(){try{const raw=localStorage.getItem(STORAGE);return raw?importState(raw):createInitialState()}catch{return createInitialState()}}
function save(){localStorage.setItem(STORAGE,serializeState(state));render()}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2200)}
function pct(v){return`${Math.round((v||0)*100)}%`}function short(id){return id?.slice(0,16)||'—'}
function renderMetrics(){const data=[['Episodes',state.episodes.length],['Staged',state.stagedIds.length],['Narratives',state.narratives.length],['Contradictions',state.contradictions.length],['Verified',state.candidates.filter(c=>c.status==='VERIFIED').length],['REM cycles',state.remCycles]];$('#metrics').innerHTML=data.map(([k,v])=>`<div class="metric"><b>${v}</b><span>${k}</span></div>`).join('')}
function renderEpisodes(){$('#episodes').innerHTML=state.episodes.length?[...state.episodes].reverse().map(ep=>`<article class="card"><div class="card-top"><div><h3>${esc(ep.text)}</h3><div class="meta">${esc(ep.eventType)} · ${esc(ep.createdAt)} · source ${esc(ep.source)}</div></div><div class="score">P ${pct(.26*ep.salience+.20*ep.novelty+.22*ep.predictionError+.14*ep.evidenceQuality+.18*Math.abs(ep.emotionalWeight))}</div></div><div class="chips">${ep.tags.map(t=>`<span class="chip">${esc(t)}</span>`).join('')}<span class="chip">evidence ${pct(ep.evidenceQuality)}</span><span class="chip">prediction Δ ${pct(ep.predictionError)}</span></div><div class="hash">${ep.id} · SHA256 ${ep.receiptHash}</div></article>`).join(''):'<div class="console">No experiences yet. Append one or load the deterministic demo.</div>'}
function renderSleep(){const n=state.nremReport;$('#sleepReport').textContent=[`WAKE episodes: ${state.episodes.length}`,`NREM staged: ${n?.staged??0}`,`NREM mean priority: ${n?pct(n.meanPriority):'—'}`,`REM cycles: ${state.remCycles}`,`Compression ratio: ${pct(compressionRatio(state))}`,`Contradictions preserved: ${state.contradictions.length}`,`Derived narratives: ${state.narratives.length}`,`Learning candidates: ${state.candidates.length}`].join('\n')}
function renderNarratives(){$('#narratives').innerHTML=state.narratives.length?state.narratives.map(n=>`<article class="card"><div class="card-top"><div><h3>${esc(n.summary)}</h3><div class="meta">${esc(n.meaning)}</div></div><div class="score">R ${pct(n.resonance)}</div></div><div class="chips"><span class="chip">evidence ${pct(n.evidence)}</span><span class="chip">contradiction ${pct(n.contradictionPressure)}</span>${n.themes.map(t=>`<span class="chip">${esc(t)}</span>`).join('')}</div><div class="hash">${n.id}<br>sources: ${n.sourceEpisodeIds.map(short).join(' · ')}</div></article>`).join(''):'<div class="console">Run NREM, then REM to derive narrative memory.</div>'}
function renderCandidates(){$('#candidates').innerHTML=state.candidates.length?state.candidates.map(c=>`<article class="card"><div class="card-top"><div><h3>${esc(c.claim)}</h3><div class="meta">${esc(c.type)} · ${c.distinctSources.length} provenance source(s)</div></div><span class="status ${c.status}">${c.status}</span></div><div class="chips"><span class="chip">resonance ${pct(c.resonance)}</span><span class="chip">evidence ${pct(c.evidence)}</span><span class="chip">contradiction ${pct(c.contradictionPressure)}</span></div><p class="meta">${c.verificationReasons.map(esc).join(' ')||'Pending verification. High resonance alone is insufficient.'}</p><div class="hash">${c.id}<br>lineage: ${c.sourceEpisodeIds.map(short).join(' · ')}</div>${c.status==='PENDING'?`<p><button data-verify="${c.id}">Verify candidate</button></p>`:''}</article>`).join(''):'<div class="console">No learning candidates yet.</div>';$$('[data-verify]').forEach(b=>b.onclick=()=>{state=verifyCandidate(state,b.dataset.verify);save();toast('Candidate verification completed.')})}
function renderChronos(){$('#chronos').innerHTML=state.chronos.length?[...state.chronos].reverse().map(r=>`<article class="card receipt"><div class="card-top"><div><h3>${esc(r.transitionId)}</h3><div class="meta">${esc(r.timestamp)} · candidate ${esc(r.candidateId)}</div></div><span class="status VERIFIED">COMMITTED</span></div><p>${esc(r.claim)}</p><div class="hash">prev ${r.previousHash}<br>hash ${r.hash}<br>sources ${r.sourceEpisodeIds.map(short).join(' · ')}</div></article>`).join(''):'<div class="console">No verified ExperienceTransitions committed.</div>'}
function renderGraph(){const svg=$('#graphSvg'),ns='http://www.w3.org/2000/svg';svg.innerHTML='';if(!state.graph.nodes.length){svg.innerHTML='<text x="500" y="310" text-anchor="middle" fill="#587086" font-size="18">Run REM to generate the resonance graph</text>';return}const pos=new Map(state.graph.nodes.map(n=>[n.id,{x:n.x*1000,y:n.y*620}]));for(const e of state.graph.edges){const a=pos.get(e.source),b=pos.get(e.target),line=document.createElementNS(ns,'line');line.setAttribute('x1',a.x);line.setAttribute('y1',a.y);line.setAttribute('x2',b.x);line.setAttribute('y2',b.y);line.setAttribute('class','edge');line.setAttribute('stroke-width',1+e.weight*5);svg.appendChild(line)}for(const n of state.graph.nodes){const p=pos.get(n.id),c=document.createElementNS(ns,'circle');c.setAttribute('cx',p.x);c.setAttribute('cy',p.y);c.setAttribute('r',9+n.activation*17);c.setAttribute('fill',`rgba(${Math.round(79+80*n.activation)},${Math.round(160+70*n.salience)},255,.82)`);c.setAttribute('class','node');c.onclick=()=>inspectNode(n.id);svg.appendChild(c);const t=document.createElementNS(ns,'text');t.setAttribute('x',p.x+20);t.setAttribute('y',p.y+4);t.setAttribute('class','node-label');t.textContent=short(n.id);svg.appendChild(t)}}
function inspectNode(id){const ep=state.episodes.find(e=>e.id===id),connected=state.graph.edges.filter(e=>e.source===id||e.target===id);$('#nodeInspector').innerHTML=`<h3>${esc(short(id))}</h3><p>${esc(ep?.text)}</p><div class="meta">source ${esc(ep?.source)}<br>receipt ${esc(ep?.receiptHash)}</div><div class="chips"><span class="chip">${connected.length} resonance edges</span><span class="chip">salience ${pct(ep?.salience)}</span></div>`}
function render(){renderMetrics();renderEpisodes();renderSleep();renderNarratives();renderCandidates();renderChronos();renderGraph()}
$('#tabs').onclick=e=>{const b=e.target.closest('button[data-tab]');if(!b)return;$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab-panel').forEach(x=>x.classList.remove('active'));$(`#tab-${b.dataset.tab}`).classList.add('active')};$$('input[type=range]').forEach(i=>i.oninput=()=>document.querySelector(`[data-out="${i.name}"]`).textContent=Number(i.value).toFixed(2));
$('#experienceForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{state=await appendExperience(state,Object.fromEntries(f.entries()));save();$('#formMsg').textContent='Episode appended + receipt generated.';e.currentTarget.elements.text.value='';toast('Immutable experience appended.')}catch(err){$('#formMsg').textContent=err.message}};
const demo=[{text:'Camera saw a bright triangular reflection crossing the window.',eventType:'vision',emotionalWeight:.3,novelty:.9,salience:.85,predictionError:.82,evidenceQuality:.9,tags:['topic:light','visual'],source:'camera-A'},{text:'Independent frame analysis saw the same triangular light reflection at the window.',eventType:'analysis',emotionalWeight:.1,novelty:.65,salience:.8,predictionError:.7,evidenceQuality:.88,tags:['topic:light','analysis'],source:'frame-analysis'},{text:'A second sensor did not detect the triangular light event.',eventType:'sensor',emotionalWeight:-.2,novelty:.7,salience:.72,predictionError:.9,evidenceQuality:.72,tags:['topic:light','sensor'],source:'sensor-B'},{text:'Music session produced a repeated minor-third motif after the visual event.',eventType:'creative',emotionalWeight:.7,novelty:.6,salience:.7,predictionError:.3,evidenceQuality:.66,tags:['topic:music','motif'],source:'session-log'},{text:'A later song session repeated the same minor-third motif during an unrelated creative session.',eventType:'creative',emotionalWeight:.5,novelty:.42,salience:.63,predictionError:.48,evidenceQuality:.75,tags:['topic:music','motif'],source:'session-log-2'}];
async function loadDemo(){state=createInitialState();for(let i=0;i<demo.length;i++)state=await appendExperience(state,demo[i],Date.UTC(2026,7,31,12,i,0));save();toast('Deterministic demo loaded.')}
$('#seedDemo').onclick=loadDemo;$('#runNrem').onclick=()=>{try{state=runNREM(state);save();toast(`NREM staged ${state.stagedIds.length} episodes.`)}catch(e){toast(e.message)}};$('#runRem').onclick=async()=>{try{state=await runREM(state);save();toast(`REM cycle ${state.remCycles} complete.`)}catch(e){toast(e.message)}};$('#verifyAll').onclick=()=>{for(const c of[...state.candidates])if(c.status==='PENDING')state=verifyCandidate(state,c.id);save();toast('All candidates evaluated under evidence/provenance gates.')};$('#commitVerified').onclick=async()=>{let n=0;for(const c of[...state.candidates])if(c.status==='VERIFIED'&&!state.chronos.some(r=>r.candidateId===c.id)){state=await commitVerifiedTransition(state,c.id,Date.now()+n);n++}save();toast(`${n} verified transition(s) committed.`)};$('#verifyChain').onclick=async()=>{const r=await verifyChronosChain(state);$('#chainStatus').textContent=r.ok?`CHAIN VALID · ${r.count} receipt(s) · head ${r.head}`:`CHAIN INVALID at ${r.index}: ${r.reason}`;toast(r.ok?'Chronos chain verified.':'Chronos chain integrity failure.')};$('#resetDerived').onclick=()=>{state={...state,stagedIds:[],nremReport:null,remCycles:0,narratives:[],candidates:[],contradictions:[],graph:{nodes:[],edges:[]},chronos:[]};save();toast('Derived state reset; raw episodes preserved.')};$('#exportBtn').onclick=()=>{const blob=new Blob([serializeState(state)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='victor-rem-lab-state.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};$('#importFile').onchange=async e=>{try{state=importState(await e.target.files[0].text());save();toast('State imported.')}catch(err){toast(err.message)}};
async function browserSelfTest(){const out=$('#self-test');out.classList.add('visible');try{await loadDemo();const raw=JSON.stringify(state.episodes);state=runNREM(state);state=await runREM(state);if(JSON.stringify(state.episodes)!==raw)throw new Error('raw episode mutation');for(const c of[...state.candidates])state=verifyCandidate(state,c.id);const vc=state.candidates.find(c=>c.status==='VERIFIED');if(!vc)throw new Error('no verifiable candidate');state=await commitVerifiedTransition(state,vc.id,Date.UTC(2026,7,31,23,0,0));const chain=await verifyChronosChain(state);if(!chain.ok)throw new Error('chain invalid');save();out.textContent=`AUTOTEST PASS | episodes=${state.episodes.length} staged=${state.stagedIds.length} rem=${state.remCycles} narratives=${state.narratives.length} contradictions=${state.contradictions.length} verified=${state.candidates.filter(c=>c.status==='VERIFIED').length} chronos=${state.chronos.length}`;document.documentElement.dataset.autotest='pass'}catch(e){out.textContent=`AUTOTEST FAIL | ${e.message}`;document.documentElement.dataset.autotest='fail'}}
render();if(new URLSearchParams(location.search).get('autotest')==='1')browserSelfTest();
