const DIM = 64;
const EMPTY_HASH = '0'.repeat(64);
export function createInitialState(){return{version:1,episodes:[],stagedIds:[],nremReport:null,remCycles:0,narratives:[],candidates:[],contradictions:[],graph:{nodes:[],edges:[]},chronos:[]}}
export function canonicalStringify(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(canonicalStringify).join(',')}]`;const keys=Object.keys(value).sort();return`{${keys.map(k=>`${JSON.stringify(k)}:${canonicalStringify(value[k])}`).join(',')}}`}
export async function sha256Hex(text){const data=new TextEncoder().encode(text);const digest=await crypto.subtle.digest('SHA-256',data);return[...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,'0')).join('')}
function clamp(v,lo=0,hi=1){const n=Number(v);if(!Number.isFinite(n))return lo;return Math.min(hi,Math.max(lo,n))}
const STOP=new Set(['the','and','that','this','with','from','were','have','has','had','for','not','but','you','your','into','out','about','after','before','then','than','they','them','their','there','here','what','when','where','why','how','was','are','is','been','being','our','ours','its','also','can','could','would','should','will','just','more','most','very','over','under','same','some']);
function words(text){return String(text||'').toLowerCase().replace(/[^a-z0-9\s-]/g,' ').split(/\s+/).filter(w=>w.length>2&&!STOP.has(w))}
function fnv1a(str){let h=0x811c9dc5;for(let i=0;i<str.length;i++){h^=str.charCodeAt(i);h=Math.imul(h,0x01000193)}return h>>>0}
export function vectorize(text,tags=[]){const vec=new Float64Array(DIM),toks=[...words(text),...tags.map(t=>`tag:${String(t).toLowerCase()}`)];for(const tok of toks){const h=fnv1a(tok),idx=h%DIM,sign=(h>>>8)&1?1:-1,weight=1+Math.min(2,tok.length/12);vec[idx]+=sign*weight}const norm=Math.hypot(...vec)||1;return Array.from(vec,x=>x/norm)}
export function cosine(a,b){if(!a||!b||a.length!==b.length)return 0;let dot=0,aa=0,bb=0;for(let i=0;i<a.length;i++){dot+=a[i]*b[i];aa+=a[i]*a[i];bb+=b[i]*b[i]}const d=Math.sqrt(aa)*Math.sqrt(bb);return d?dot/d:0}
function normalizeTags(tags){if(Array.isArray(tags))return[...new Set(tags.map(t=>String(t).trim()).filter(Boolean))].slice(0,12);return[...new Set(String(tags||'').split(',').map(t=>t.trim()).filter(Boolean))].slice(0,12)}
export async function createExperience(input,nowMs=Date.now()){const text=String(input.text||'').trim();if(text.length<3)throw new Error('Experience text must be at least 3 characters.');const tags=normalizeTags(input.tags),base={createdAt:new Date(nowMs).toISOString(),eventType:String(input.eventType||'observation').trim().slice(0,40),text,emotionalWeight:clamp(input.emotionalWeight,-1,1),novelty:clamp(input.novelty),salience:clamp(input.salience),predictionError:clamp(input.predictionError),evidenceQuality:clamp(input.evidenceQuality),tags,source:String(input.source||'manual').trim().slice(0,120)||'manual'};const receiptHash=await sha256Hex(canonicalStringify(base)),id=`EP-${receiptHash.slice(0,12)}`,embedding=vectorize(base.text,tags);return Object.freeze({...base,id,receiptHash,embedding})}
function freezeEpisodes(state){state.episodes=state.episodes.map(ep=>Object.freeze({...ep,tags:[...ep.tags],embedding:[...ep.embedding]}));return state}
export async function appendExperience(state,input,nowMs=Date.now()){const next=structuredClone(state),ep=await createExperience(input,nowMs);if(next.episodes.some(e=>e.receiptHash===ep.receiptHash))return freezeEpisodes(next);next.episodes.push(ep);return freezeEpisodes(next)}
export function experiencePriority(ep){return ep.salience*.26+ep.novelty*.20+ep.predictionError*.22+ep.evidenceQuality*.14+Math.abs(ep.emotionalWeight)*.18}
export function stageForNREM(state,maxItems=10){return[...state.episodes].sort((a,b)=>experiencePriority(b)-experiencePriority(a)||a.id.localeCompare(b.id)).slice(0,maxItems).map(e=>e.id)}
export function runNREM(state,maxItems=10){const next=structuredClone(state),stagedIds=stageForNREM(next,maxItems),staged=stagedIds.map(id=>next.episodes.find(e=>e.id===id));next.stagedIds=stagedIds;next.nremReport={staged:stagedIds.length,meanPriority:staged.length?staged.reduce((s,e)=>s+experiencePriority(e),0)/staged.length:0,sourceReceipts:staged.map(e=>e.receiptHash)};return freezeEpisodes(next)}
function topicTags(ep){return ep.tags.filter(t=>t.toLowerCase().startsWith('topic:')).map(t=>t.toLowerCase())}
function polarity(text){return/\b(no|not|never|cannot|can't|false|wrong|didn't|doesn't|isn't|wasn't|without)\b/i.test(text)?-1:1}
export function detectContradiction(a,b){const ta=new Set(topicTags(a)),shared=topicTags(b).filter(t=>ta.has(t));if(!shared.length||polarity(a.text)===polarity(b.text))return null;return{a:a.id,b:b.id,topics:shared.sort()}}
function pairKey(a,b){return[a,b].sort().join('::')}
function topTerms(episodes,limit=5){const counts=new Map();for(const ep of episodes){for(const w of new Set(words(ep.text)))counts.set(w,(counts.get(w)||0)+1);for(const tag of ep.tags)counts.set(tag.toLowerCase(),(counts.get(tag.toLowerCase())||0)+1.25)}return[...counts.entries()].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,limit).map(([term])=>term)}
function connectedComponents(ids,edges){const adj=new Map(ids.map(id=>[id,[]]));for(const e of edges){adj.get(e.source)?.push(e.target);adj.get(e.target)?.push(e.source)}const seen=new Set(),comps=[];for(const id of ids){if(seen.has(id))continue;const q=[id],comp=[];seen.add(id);while(q.length){const cur=q.shift();comp.push(cur);for(const n of adj.get(cur)||[])if(!seen.has(n)){seen.add(n);q.push(n)}}comps.push(comp.sort())}return comps.sort((a,b)=>a[0].localeCompare(b[0]))}
function buildGraph(episodes){const nodes=episodes.map((ep,i)=>{const angle=i*Math.PI*(3-Math.sqrt(5)),r=.34+.52*Math.sqrt((i+1)/Math.max(1,episodes.length));return{id:ep.id,x:.5+Math.cos(angle)*r*.46,y:.5+Math.sin(angle)*r*.46,activation:experiencePriority(ep),eventType:ep.eventType,salience:ep.salience}}),edges=[];for(let i=0;i<episodes.length;i++)for(let j=i+1;j<episodes.length;j++){const a=episodes[i],b=episodes[j],sim=Math.max(0,cosine(a.embedding,b.embedding)),sharedTopic=topicTags(a).some(t=>topicTags(b).includes(t)),weight=sharedTopic?Math.max(sim,.42):sim;if(weight>=.30)edges.push({source:a.id,target:b.id,weight})}return{nodes,edges}}
function mean(arr){return arr.length?arr.reduce((a,b)=>a+b,0)/arr.length:0}
export async function runREM(state){const next=structuredClone(state);if(!next.stagedIds.length)throw new Error('Run NREM staging before REM.');const episodes=next.stagedIds.map(id=>next.episodes.find(e=>e.id===id)).filter(Boolean),graph=buildGraph(episodes);next.graph=graph;const cm=new Map();for(let i=0;i<episodes.length;i++)for(let j=i+1;j<episodes.length;j++){const c=detectContradiction(episodes[i],episodes[j]);if(c)cm.set(pairKey(c.a,c.b),c)}next.contradictions=[...cm.values()];const comps=connectedComponents(episodes.map(e=>e.id),graph.edges),narratives=[],candidates=[],cycle=next.remCycles+1;for(const ids of comps){const eps=ids.map(id=>episodes.find(e=>e.id===id)),terms=topTerms(eps,6),relatedEdges=graph.edges.filter(e=>ids.includes(e.source)&&ids.includes(e.target)),resonance=Math.min(1,.25+.12*ids.length+mean(relatedEdges.map(e=>e.weight))*.45),evidence=mean(eps.map(e=>e.evidenceQuality)),pri=mean(eps.map(experiencePriority)),pairCount=Math.max(1,ids.length*(ids.length-1)/2),contrad=next.contradictions.filter(c=>ids.includes(c.a)&&ids.includes(c.b)),contradictionPressure=Math.min(1,contrad.length/pairCount),sourceEpisodeIds=[...ids].sort(),narrativeSeed={cycle,sourceEpisodeIds,terms,resonance,evidence,contradictionPressure},nidHash=await sha256Hex(canonicalStringify(narrativeSeed));const narrative={id:`NAR-${nidHash.slice(0,12)}`,cycle,sourceEpisodeIds,summary:ids.length===1?`Single high-priority experience centered on ${terms.slice(0,3).join(', ')||'an unresolved event'}.`:`Recurring cluster across ${ids.length} experiences centered on ${terms.slice(0,4).join(', ')||'shared context'}.`,meaning:contradictionPressure>0?'The cluster is structurally important but internally contested; preserve both interpretations and investigate.':pri>.67?'The cluster carries enough salience/prediction error to justify durable review and future-model testing.':'The cluster is a candidate abstraction, not a verified conclusion.',themes:terms,resonance,evidence,contradictionPressure,contradictions:contrad,derivedOnly:true};narratives.push(narrative);const cidHash=await sha256Hex(canonicalStringify({sourceEpisodeIds,claim:narrative.summary,cycle}));candidates.push({id:`CAND-${cidHash.slice(0,12)}`,cycle,type:ids.length>1?'WORLD_MODEL_PATTERN':'EPISODIC_INSIGHT',claim:narrative.summary,sourceEpisodeIds,sourceReceipts:eps.map(e=>e.receiptHash),distinctSources:[...new Set(eps.map(e=>e.source))].sort(),resonance,evidence,contradictionPressure,status:'PENDING',verificationReasons:[],derivedOnly:true})}next.remCycles=cycle;next.narratives=narratives;next.candidates=candidates;return freezeEpisodes(next)}
export function verifyCandidate(state,candidateId){const next=structuredClone(state),c=next.candidates.find(x=>x.id===candidateId);if(!c)throw new Error(`Candidate not found: ${candidateId}`);const reasons=[];if(c.sourceEpisodeIds.length<2)reasons.push('Needs at least two source episodes for pattern canonization.');if(c.distinctSources.length<2)reasons.push('Needs at least two distinct provenance sources.');if(c.evidence<.65)reasons.push(`Evidence quality ${c.evidence.toFixed(2)} is below 0.65.`);if(c.contradictionPressure>.35)reasons.push(`Contradiction pressure ${c.contradictionPressure.toFixed(2)} exceeds 0.35.`);if(c.sourceEpisodeIds.some(id=>!next.episodes.some(e=>e.id===id)))reasons.push('Source lineage is incomplete.');if(c.resonance>=.8&&c.evidence<.65)reasons.push('Resonance alone cannot establish truth.');c.status=reasons.length?'REJECTED':'VERIFIED';c.verificationReasons=reasons.length?reasons:['Evidence, provenance diversity, contradiction pressure, and source lineage passed.'];return freezeEpisodes(next)}
export async function commitVerifiedTransition(state,candidateId,nowMs=Date.now()){const next=structuredClone(state),c=next.candidates.find(x=>x.id===candidateId);if(!c)throw new Error(`Candidate not found: ${candidateId}`);if(c.status!=='VERIFIED')throw new Error('Only VERIFIED candidates may be committed.');if(next.chronos.some(r=>r.candidateId===candidateId))return freezeEpisodes(next);const previousHash=next.chronos.length?next.chronos[next.chronos.length-1].hash:EMPTY_HASH,payload={index:next.chronos.length,timestamp:new Date(nowMs).toISOString(),transitionId:`XT-${c.id.slice(5)}`,candidateId:c.id,claim:c.claim,sourceEpisodeIds:[...c.sourceEpisodeIds],sourceReceipts:[...c.sourceReceipts],previousHash},hash=await sha256Hex(canonicalStringify(payload));next.chronos.push({...payload,hash});return freezeEpisodes(next)}
export async function verifyChronosChain(state){let prev=EMPTY_HASH;for(let i=0;i<state.chronos.length;i++){const r=state.chronos[i];if(r.index!==i||r.previousHash!==prev)return{ok:false,index:i,reason:'Link/index mismatch'};const payload={index:r.index,timestamp:r.timestamp,transitionId:r.transitionId,candidateId:r.candidateId,claim:r.claim,sourceEpisodeIds:r.sourceEpisodeIds,sourceReceipts:r.sourceReceipts,previousHash:r.previousHash},expected=await sha256Hex(canonicalStringify(payload));if(expected!==r.hash)return{ok:false,index:i,reason:'Hash mismatch'};prev=r.hash}return{ok:true,count:state.chronos.length,head:prev}}
export function compressionRatio(state){return state.stagedIds.length?1-state.narratives.length/state.stagedIds.length:0}
export function serializeState(state){return JSON.stringify(state,null,2)}
export function importState(json){const parsed=JSON.parse(json);if(!parsed||parsed.version!==1||!Array.isArray(parsed.episodes))throw new Error('Invalid Victor REM Lab state file.');return freezeEpisodes(parsed)}
